---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-6
- name: centos-7
- name: debian-6
  run_list: recipe[apt]
- name: debian-7
  run_list: recipe[apt]
- name: debian-8
  run_list: recipe[apt]
- name: fedora-20
- name: fedora-21
- name: oraclelinux-6
  driver_config:
    platform: rhel
- name: oraclelinux-7
  driver_config:
    platform: rhel
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-14.10
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]

# Non-official images
- name: scientific-6.6
  driver_config:
    image: ringo/scientific:6.6
    platform: rhel
- name: scientific-7.1
  driver_config:
    image: ringo/scientific:7.1
    platform: rhel
