---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
platforms:
# - name: centos-5.9
- name: centos-6.6
- name: centos-7.0
- name: debian-6.0.10
  run_list: [ "recipe[apt]" ]
- name: debian-7.7
  run_list: [ "recipe[apt]" ]
- name: fedora-19
- name: fedora-20
- name: freebsd-10.0
- name: ubuntu-10.04
  run_list: [ "recipe[apt]" ]
- name: ubuntu-12.04
  run_list: [ "recipe[apt]" ]
- name: ubuntu-14.04
  run_list: [ "recipe[apt]" ]

suites:
- name: default
  run_list:
  - recipe[git-ssh-server_test::default]
  attributes: {}
- name: lwrp
  run_list:
  - recipe[git-ssh-server_test::lwrp]
  attributes: {}
