---
driver:
  name: vagrant
  vm_hostname: 'git-ssh-server.local'

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: centos-5.11
- name: centos-6.7
- name: centos-7.1
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.8
  run_list: recipe[apt]
- name: fedora-21
- name: opensuse-13.2
  driver_config:
    box: opscode-opensuse-13.2
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.2-x86_64_chef-provisionerless.box
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]

suites:
- name: default
  run_list: recipe[git-ssh-server_test]
