---
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

platforms:
- name: centos-5-8-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-6-5-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-6-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: recipe[apt]

- name: debian-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: recipe[apt]

- name: fedora-19-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: fedora-20-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: ubuntu-10-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: recipe[apt]

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: recipe[apt]

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: recipe[apt]

- name: amazon-2011.02.1
  driver_plugin: ec2
  driver_config:
    image_id: ami-8e1fece7
    flavor_id: t1.micro
    username: ec2-user
<% if ENV['SSH_AGENT_PID'].nil? %>
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
<% end %>

- name: amazon-2013.09.2
  driver_plugin: ec2
  driver_config:
    image_id: ami-bba18dd2
    flavor_id: t1.micro
    username: ec2-user
<% if ENV['SSH_AGENT_PID'].nil? %>
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
<% end %>
