rvm:
- 1.9.3
- 2.0.0
- 2.1
- 2.2

sudo: true

env:
  matrix:
  - TESTS="style unit" CHEF_VERSION="~> 11.0"
  - TESTS="style unit" CHEF_VERSION="~> 12.0"
  - TESTS="integration:docker[centos-6]"
  - TESTS="integration:docker[centos-7]"
  - TESTS="integration:docker[debian-6]"
  - TESTS="integration:docker[debian-7]"
  - TESTS="integration:docker[debian-8]"
  - TESTS="integration:docker[fedora-20]"
  - TESTS="integration:docker[oraclelinux-7]"
  - TESTS="integration:docker[ubuntu-1204]"
  - TESTS="integration:docker[ubuntu-1404]"
  - TESTS="integration:docker[ubuntu-1410]"
  - TESTS="integration:docker[ubuntu-1504]"
  - TESTS="integration:docker[scientific-66]"

matrix:
  exclude:
  - rvm: 1.9.3
    env: TESTS="style unit" CHEF_VERSION="~> 12.0"
  - rvm: 2.2
    env: TESTS="style unit" CHEF_VERSION="~> 11.0"
  - rvm: 1.9.3
    env: TESTS="integration:docker[centos-6]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[centos-6]"
  - rvm: 2.1
    env: TESTS="integration:docker[centos-6]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[centos-7]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[centos-7]"
  - rvm: 2.1
    env: TESTS="integration:docker[centos-7]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[debian-6]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[debian-6]"
  - rvm: 2.1
    env: TESTS="integration:docker[debian-6]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[debian-7]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[debian-7]"
  - rvm: 2.1
    env: TESTS="integration:docker[debian-7]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[debian-8]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[debian-8]"
  - rvm: 2.1
    env: TESTS="integration:docker[debian-8]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[fedora-20]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[fedora-20]"
  - rvm: 2.1
    env: TESTS="integration:docker[fedora-20]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[oraclelinux-7]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[oraclelinux-7]"
  - rvm: 2.1
    env: TESTS="integration:docker[oraclelinux-7]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[ubuntu-1204]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[ubuntu-1204]"
  - rvm: 2.1
    env: TESTS="integration:docker[ubuntu-1204]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[ubuntu-1404]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[ubuntu-1404]"
  - rvm: 2.1
    env: TESTS="integration:docker[ubuntu-1404]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[ubuntu-1410]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[ubuntu-1410]"
  - rvm: 2.1
    env: TESTS="integration:docker[ubuntu-1410]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[ubuntu-1504]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[ubuntu-1504]"
  - rvm: 2.1
    env: TESTS="integration:docker[ubuntu-1504]"
  - rvm: 1.9.3
    env: TESTS="integration:docker[scientific-66]"
  - rvm: 2.0.0
    env: TESTS="integration:docker[scientific-66]"
  - rvm: 2.1
    env: TESTS="integration:docker[scientific-66]"

bundler_args: --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.3.0/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake $TESTS

after_failure: cat docker_daemon.log
